# Ejercicios Complemetarios
## Ejercicios de Normalizción y Estandarización
---
### Ejercicio 1: Normalización Max-Min

In [1]:
import numpy as np

datos = np.array([10,20,30,40,50])

def Xnormalize(datosX):
    xMin = datosX.min()
    xMax = datosX.max()
    return (datosX - xMin) / (xMax -xMin)

normalized_data = Xnormalize(datos)
print(normalized_data)

[0.   0.25 0.5  0.75 1.  ]


### Ejercicio 2: Estandarización (Z-Score)


In [ ]:
import numpy as np

datos = np.array([2,4,4,4,5,5,7,9])

#desviación estandar
desviacion = np.std(datos)

    #sacar media
media = sum(datos) / len(datos)

# estandarizar cada valor
ZEstandar = (datos - media) / desviacion

print(f'desviacion: {desviacion}')
print(f'media: {media}')
print(f'estandarización: {ZEstandar}')


desviacion: 2.0
media: 5.0
estandarización: [-1.5 -0.5 -0.5 -0.5  0.   0.   1.   2. ]


### Ejercicio 3: Comparación de Tecnicas

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler


datos = np.array([100, 200, 300, 400, 500]).reshape(-1, 1)

# Aplicar:
# 1. MinMaxScaler de sklearn
MMScaler = MinMaxScaler()
datosMMScaler = MMScaler.fit_transform(datos)

# 2. StandardScaler de sklearn
SSScaler = StandardScaler()
datosSSScaler = SSScaler.fit_transform(datos)

print("- - MinMaxScaler - -")
print(datosMMScaler)

print("\n- - StandarScaler - -")
print(datosSSScaler)
# Comparar resultados




- - MinMaxScaler - -
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]

- - StandarScaler - -
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


## Ejercicios de Manejo de Valores Faltantes
---
### Ejericio 4: Identificación de Valores faltantes

In [15]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [1, 2, 3, 4, 5]
})

# Ejercicios:
# 1. Identificar valores faltantes con isnull()
nulos = df.isnull()
# 2. Contar valores faltantes por columna
contarNulos = df.isnull().sum()
# 3. Calcular porcentaje de valores faltantes
porcenNulos = (df.isnull().sum() / len(df)) * 100
# 4. Mostrar solo filas con valores faltantes
filasnulos= df[df.isnull().any(axis=1)]

print("- - Conteo de Nulos - -")
print(contarNulos)

print("\n- - Porcentaje de Nulos - -")
print(porcenNulos)

print("\n--- Filas con Nulos - -")
print(filasnulos)

- - Conteo de Nulos - -
A    1
B    2
C    0
dtype: int64

- - Porcentaje de Nulos - -
A    20.0
B    40.0
C     0.0
dtype: float64

--- Filas con Nulos - -
     A    B  C
0  1.0  NaN  1
2  NaN  3.0  3
4  5.0  NaN  5


### Ejercicio 5: Estrategias de Imputación

In [22]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [1, 2, 3, 4, 5]
})

# Para el mismo DataFrame, aplicar:
# 1. Eliminar filas con valores faltantes
noFilas = df.dropna()
# 2. Eliminar columnas con valores faltantes
noColumnas = df.dropna(axis=1)
# 3. Imputar con la media
imputarMedia = df.fillna(df.mean())
# 4. Imputar con la mediana
imputarMediana = df.fillna(df.median())
# 5. Imputar con forward fill
FFill = df.ffill()
# 6. Imputar con backward fill
BFill = df.bfill()


print(df)

print("\n- - no Filas - -")
print(noFilas)

print("\n- - no columnas - -")
print(noColumnas)

print("\n- - Media - -")
print(imputarMedia)
print("\n- - Mediana - -")
print(imputarMediana)
print("\n- - Forward Fill - -")
print(FFill)
print("\n- - Backward Fill - -")
print(BFill)


     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  NaN  3.0  3
3  4.0  4.0  4
4  5.0  NaN  5

- - no Filas - -
     A    B  C
1  2.0  2.0  2
3  4.0  4.0  4

- - no columnas - -
   C
0  1
1  2
2  3
3  4
4  5

- - Media - -
     A    B  C
0  1.0  3.0  1
1  2.0  2.0  2
2  3.0  3.0  3
3  4.0  4.0  4
4  5.0  3.0  5

- - Mediana - -
     A    B  C
0  1.0  3.0  1
1  2.0  2.0  2
2  3.0  3.0  3
3  4.0  4.0  4
4  5.0  3.0  5

- - Forward Fill - -
     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  2.0  3.0  3
3  4.0  4.0  4
4  5.0  4.0  5

- - Backward Fill - -
     A    B  C
0  1.0  2.0  1
1  2.0  2.0  2
2  4.0  3.0  3
3  4.0  4.0  4
4  5.0  NaN  5


### Ejercicio 6: Imputación Avanzada

In [25]:
# Usar sklearn.impute.SimpleImputer


import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

# mismo df
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [1, 2, 3, 4, 5]
})

# Probar diferentes estrategias:
# - mean
usarMean = SimpleImputer(strategy='mean')
dfMean = pd.DataFrame(usarMean.fit_transform(df), columns=df.columns)
# - median
usarMedian = SimpleImputer(strategy='median')
dfMedian = pd.DataFrame(usarMedian.fit_transform(df), columns=df.columns)
# - most_frequent
usarMostFq = SimpleImputer(strategy='most_frequent')
dfMostFq = pd.DataFrame(usarMostFq.fit_transform(df), columns=df.columns)
# - constant
usarConstant = SimpleImputer(strategy='constant', fill_value=0)
dfConstant = pd.DataFrame(usarConstant.fit_transform(df), columns=df.columns)

print("- - Media - -")
print(dfMean)

print("\n- - Constante - -")
print(dfConstant)

- - Media - -
     A    B    C
0  1.0  3.0  1.0
1  2.0  2.0  2.0
2  3.0  3.0  3.0
3  4.0  4.0  4.0
4  5.0  3.0  5.0

- - Constante - -
     A    B    C
0  1.0  0.0  1.0
1  2.0  2.0  2.0
2  0.0  3.0  3.0
3  4.0  4.0  4.0
4  5.0  0.0  5.0


## Ejercicios de Detección y Manejo de Outliers
---
### Ejercicio 7: Metodo IQR (Rango Intercuartil)

In [30]:
import numpy as np

datos = [10, 12, 14, 15, 16, 18, 20, 22, 25, 100]

# Calcular:
# 1. Q1 (percentil 25)
q1 = np.percentile(datos, 25)
# 2. Q3 (percentil 75)
q3 = np.percentile(datos, 75)
# 3. IQR = Q3 - Q1
iqr = q3 - q1
# 4. Límite inferior = Q1 - 1.5 * IQR
inferior = q1 - 1.5 * iqr

# 5. Límite superior
superior = q3 + 1.5 * iqr

# 6. Identificar outliers
outliers = [x for x in datos if x < inferior or x > superior]

print(f"Q1: {q1}")
print(f"Q3: {q3}")
print(f"IQR: {iqr}")
print(f"Límites: {inferior} a {superior}")
print(f"Outliers detectados: {outliers}")


Q1: 14.25
Q3: 21.5
IQR: 7.25
Límites: 3.375 a 32.375
Outliers detectados: [100]


### Ejercicio 8: Metodo Z-Scotr

In [32]:
from scipy import stats
import numpy as np

datos = np.array([10, 12, 14, 15, 16, 18, 20, 22, 25, 100])

# Calcular Z-scores y encontrar valores donde |Z| > 3
z_scores = stats.zscore(datos)
outliers = np.where(np.abs(z_scores) > 3)

print(f"Z-scores de cada dato:\n{np.round(z_scores, 2)}")
print(f"\nValores donde |Z| > 3 (Outliers): {outliers}")


Z-scores de cada dato:
[-0.6  -0.52 -0.44 -0.4  -0.36 -0.28 -0.21 -0.13 -0.01  2.96]

Valores donde |Z| > 3 (Outliers): (array([], dtype=int64),)


### Ejercicio 9: Manejo de Outliers

In [34]:
from scipy import stats
import numpy as np

datos = np.array([10, 12, 14, 15, 16, 18, 20, 22, 25, 100])

q1, q3 = np.percentile(datos, 25), np.percentile(datos, 75)
iqr = q3 - q1
limiteSup = q3 + 1.5 * iqr
limiteInf = q1 - 1.5 * iqr

# Opciones para manejar outliers:
# 1. Eliminar outliers
eliminar = datos[(datos >= limiteInf) & (datos <= limiteSup)]
# 2.替换为边界值 (capping)
capping = np.clip(datos, limiteInf, limiteSup)
# 3. Transformación logarítmica
datosLog = np.log(datos)
# 4. Transformación Box-Cox
datosBoxcox, lmbda = stats.boxcox(datos)
# Aplicar cada método

print(f"Original: {datos}")
print(f"1. Eliminados: {eliminar}")
print(f"2. Capping: {np.round(capping, 2)}")
print(f"3. Logarítmica: {np.round(datosLog, 2)}")
print(f"4. Box-Cox: {np.round(datosBoxcox, 2)}")

Original: [ 10  12  14  15  16  18  20  22  25 100]
1. Eliminados: [10 12 14 15 16 18 20 22 25]
2. Capping: [10.   12.   14.   15.   16.   18.   20.   22.   25.   32.38]
3. Logarítmica: [2.3  2.48 2.64 2.71 2.77 2.89 3.   3.09 3.22 4.61]
4. Box-Cox: [0.84 0.85 0.86 0.86 0.87 0.87 0.88 0.88 0.88 0.9 ]


---
## Ejercicios de Transformación de Variables
---
### Ejercicio 10: Codificación de Variables Categorícas

In [46]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({
    'color': ['rojo', 'azul', 'verde', 'rojo', 'verde'],
    'talla': ['S', 'M', 'L', 'S', 'M']
})

# Aplicar:
# 1. Label Encoding
encoderColor = LabelEncoder()
encoderTalla = LabelEncoder()

df['color_cod'] = encoderColor.fit_transform(df['color'])
df['talla_cod'] = encoderTalla.fit_transform(df['talla'])

print("- - LabelEncoding - -")
print(df)

mappingColor = dict(zip(encoderColor.classes_, encoderColor.transform(encoderColor.classes_)))
mappingTalla = dict(zip(encoderTalla.classes_, encoderTalla.transform(encoderTalla.classes_)))

print(f'Mapeo de color: {mappingColor}')
print(f'Mapeo de talla: {mappingTalla}')


# 2. One-Hot Encoding con get_dummies
dummies = pd.get_dummies(df['color'], prefix='color')

print("\n- - One-Hot con get_dummies - -")
print(dummies)

# 3. One-Hot Encoding con sklearn
encoder = OneHotEncoder(sparse_output=False)
resultado = encoder.fit_transform(df[['color']])

columnas = encoder.get_feature_names_out(['color'])
dfSklearn = pd.DataFrame(resultado, columns = columnas)

print('\n - - One Hot - -')
print(dfSklearn)


- - LabelEncoding - -
   color talla  color_cod  talla_cod
0   rojo     S          1          2
1   azul     M          0          1
2  verde     L          2          0
3   rojo     S          1          2
4  verde     M          2          1
Mapeo de color: {'azul': np.int64(0), 'rojo': np.int64(1), 'verde': np.int64(2)}
Mapeo de talla: {'L': np.int64(0), 'M': np.int64(1), 'S': np.int64(2)}

- - One-Hot con get_dummies - -
   color_azul  color_rojo  color_verde
0       False        True        False
1        True       False        False
2       False       False         True
3       False        True        False
4       False       False         True

 - - One Hot - -
   color_azul  color_rojo  color_verde
0         0.0         1.0          0.0
1         1.0         0.0          0.0
2         0.0         0.0          1.0
3         0.0         1.0          0.0
4         0.0         0.0          1.0


### Ejercicio 11: Transformaciones Númericas

In [48]:
import numpy as np

datos = [1, 2, 3, 4, 5, 10, 20, 30]

# Aplicar:
# 1. Logaritmo natural
datosLog = np.log(datos)
# 2. Raíz cuadrada
datosSqrt = np.sqrt(datos)
# 3. Transformación Box-Cox
datosBoxCox , lmbda = stats.boxcox(datos)
# 4. Discretización (binned)
datosBinned = pd.cut(datos, bins=3, labels=["Bajo", "Medio", "Alto"])
resultados = pd.DataFrame({
    'Original': datos,
    'Log': np.round(datosLog, 2),
    'Sqrt': np.round(datosSqrt, 2),
    'Box-Cox': np.round(datosBoxCox, 2),
    'Binned': datosBinned
})

print(resultados)

   Original   Log  Sqrt  Box-Cox Binned
0         1  0.00  1.00     0.00   Bajo
1         2  0.69  1.41     0.67   Bajo
2         3  1.10  1.73     1.05   Bajo
3         4  1.39  2.00     1.31   Bajo
4         5  1.61  2.24     1.51   Bajo
5        10  2.30  3.16     2.10   Bajo
6        20  3.00  4.47     2.66  Medio
7        30  3.40  5.48     2.97   Alto


### Ejercicio 12: Feature Engineering

In [49]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

# Creamos un DataFrame de ejemplo
df = pd.DataFrame({
    'ventas': [100, 150, 200, 50, 300],
    'clientes': [10, 15, 25, 5, 30],
    'costo': [80, 120, 150, 60, 200],
    'fecha': pd.to_datetime(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04', '2026-01-05'])
})

# 1. Ratio entre dos columnas
df['ticket_promedio'] = df['ventas'] / df['clientes']
# 2. Diferencia entre columnas
df['ganancia'] = df['ventas'] - df['costo']
# 3. Agregar indicadores binarios
df['es_venta_alta'] = (df['ventas'] > 150).astype(int)
# 4. Polynomial Features
poly = PolynomialFeatures(degree=2, include_bias=False)
poly_data = poly.fit_transform(df[['ventas', 'costo']])
df_poly = pd.DataFrame(poly_data, columns=poly.get_feature_names_out(['ventas', 'costo']))
# 5. DateTime features
df['dia_semana'] = df['fecha'].dt.day_name()
df['es_fin_de_semana'] = df['fecha'].dt.dayofweek.isin([5, 6]).astype(int)
df['mes'] = df['fecha'].dt.month

print("- - DataFrame - -")
print(df)
print("\n- - Polynomial Features - -")
print(df_poly.head())

- - DataFrame - -
   ventas  clientes  costo      fecha  ticket_promedio  ganancia  \
0     100        10     80 2026-01-01             10.0        20   
1     150        15    120 2026-01-02             10.0        30   
2     200        25    150 2026-01-03              8.0        50   
3      50         5     60 2026-01-04             10.0       -10   
4     300        30    200 2026-01-05             10.0       100   

   es_venta_alta dia_semana  es_fin_de_semana  mes  
0              0   Thursday                 0    1  
1              0     Friday                 0    1  
2              1   Saturday                 1    1  
3              0     Sunday                 1    1  
4              1     Monday                 0    1  

- - Polynomial Features - -
   ventas  costo  ventas^2  ventas costo  costo^2
0   100.0   80.0   10000.0        8000.0   6400.0
1   150.0  120.0   22500.0       18000.0  14400.0
2   200.0  150.0   40000.0       30000.0  22500.0
3    50.0   60.0    2500.0

---
## Ejercicios de Escalamiento de Datos
---
### Ejercicio 13: Comparar Escaladores

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler
import numpy as np
import pandas as pd

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Aplicar cada escalador y comparar resultados
# ¿Cuándo usar cada uno?
minMax = MinMaxScaler().fit_transform(data)
standard = StandardScaler().fit_transform(data)
robust = RobustScaler().fit_transform(data)
maxAbs = MaxAbsScaler().fit_transform(data)


print("--- Datos Originales ---")
print(data)
print("\n--- MinMaxScaler (0 a 1) ---")
print(np.round(minMax, 2))
print("\n--- StandardScaler (Media 0) ---")
print(np.round(standard, 2))
print("\n--- RobustScaler (Resistente a Outliers) ---")
print(np.round(robust, 2))
print("\n--- MaxAbsScaler (-1 a 1) ---")
print(np.round(maxAbs, 2))

--- Datos Originales ---
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

--- MinMaxScaler (0 a 1) ---
[[0.   0.   0.  ]
 [0.33 0.33 0.33]
 [0.67 0.67 0.67]
 [1.   1.   1.  ]]

--- StandardScaler (Media 0) ---
[[-1.34 -1.34 -1.34]
 [-0.45 -0.45 -0.45]
 [ 0.45  0.45  0.45]
 [ 1.34  1.34  1.34]]

--- RobustScaler (Resistente a Outliers) ---
[[-1.   -1.   -1.  ]
 [-0.33 -0.33 -0.33]
 [ 0.33  0.33  0.33]
 [ 1.    1.    1.  ]]

--- MaxAbsScaler (-1 a 1) ---
[[0.1  0.18 0.25]
 [0.4  0.45 0.5 ]
 [0.7  0.73 0.75]
 [1.   1.   1.  ]]


### Ejercicio 14: Pipeline de Preprocesamineto

In [52]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer


df = pd.DataFrame({
    'edad': [25, 30, np.nan, 45, 22],
    'salario': [50000, 60000, 120000, np.nan, 30000],
    'ciudad': ['Queretaro', 'CDMX', 'Queretaro', 'Monterrey', 'CDMX'],
    'prioridad': ['Alta', 'Baja', 'Media', 'Alta', 'Baja']
})

# 1. Seleccionar columnas numéricas y categóricas
colNum = ['edad', 'salario']
cols_categoricas = ['ciudad', 'prioridad']

# 2. Aplicar transformaciones apropiadas
numTransf = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

catTransform = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

#3. Combinar en un pipline
preprocesador = ColumnTransformer(
    transformers=[
        ('num', numTransf, colNum),
        ('cat', catTransform, cols_categoricas)
    ])
pipelineF = Pipeline(steps=[('prepro', preprocesador)])
datoslisto = pipelineF.fit_transform(df)

print("--- Matriz resultante lista para el modelo ---")
print(datoslisto)

--- Matriz resultante lista para el modelo ---
[[-0.61230868 -0.42953209  0.          0.          1.          1.
   0.          0.        ]
 [ 0.0124961  -0.09912279  1.          0.          0.          0.
   1.          0.        ]
 [-0.29990629  1.88333301  0.          0.          1.          0.
   0.          1.        ]
 [ 1.88691043 -0.26432744  0.          1.          0.          1.
   0.          0.        ]
 [-0.98719155 -1.09035069  1.          0.          0.          0.
   1.          0.        ]]
